# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e61d514d3c50440263110fca8251a1575b84e9005af7a7fe901027de4b88143a4bbc412ba0638a6bf7aef1fcdd7049a0bb862c6f8bc24d162b43bba6ac8d388c

test:
  secret_key_base: 003aecd7d092811a6cc83623cccd1dfd17e77a1be5271673ee3ce4dee1ded8df0ab4cd9d1595e98da5c55496c38684396d05e5fda9b31f9fb567f8358489802c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
